### ISSUE TITLE
3d_armor_ui errors when moreores is enabled

### ISSUE THREAD

**Issue by s3rvant** [minetest-mods/3d_armor#101]
Minetest version 5.7.0 running on Ubuntu 22.04
3d_armor version 2023-02-06
moreores version 2023-02-12 (also tried 2023-01-26)

After starting server receive error:

```
ERROR[Main]: ModError: Failed to load and run script from /home/minetest/minetestserver/bin/../mods/3d_armor/3d_armor_ui/init.lua:
ERROR[Main]: ...minetestserver/bin/../mods/3d_armor/3d_armor_ui/init.lua:12: attempt to index local 'ui' (a boolean value)
ERROR[Main]: stack traceback:
ERROR[Main]:       ...minetestserver/bin/../mods/3d_armor/3d_armor_ui/init.lua:12: in main chunk
```

Disabling moreores removes the error and works as expected though of course without the optional dependency.

**Comment by fluxionary** [comment]
something is over-writing the `unified_inventory` global w/ a boolean. this is most likely due to a mod *other* than 3d_armor, unified_inventory, or moreores. it is probably something that depends on moreores though, if the problem disappears when that is disabled. 

is it possible to get a list of which mods you are also running, with versions if possible?

**Comment by s3rvant** [comment]
Thank you this was indeed the issue.

I setup a new world with fewer mods to address a separate issue and moreores was able to load there as well.
